---
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/gcp-gke-control-plane-auth-networks-updater/'
    schedule:
      interval: 'daily'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
