# Copyright 2021 METRO Digital GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: GKE Control Plane Authorised Networks Updater
description: |-
  Adds or removes the runner's public IP to or from the control plane authorised
  networks for a given GKE cluster.
inputs:
  project_id:
    description: |-
      The ID of the project in which the GKE cluster is located
    required: true
  location:
    description: |-
      GKE cluster location (like europe-west1)
    required: true
  cluster_name:
    description: |-
      The name of the GKE cluster
    required: true
  mode:
    description: |-
      Operation mode, can be 'add' or 'remove'
    required: false
    default: 'add'
  description:
    description: |-
      Description added to the created /32 entry
    required: false
    default: 'GitHub Action runner'
runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
branding:
  color: red
  icon: eye-off
