---
name: Test Create Jira issue custom GitHub Action

on:  # yamllint disable-line rule:truthy
  pull_request:

permissions:
  pull-requests: write
  contents: read

defaults:
  run:
    shell: bash
    working-directory: jira-create-issue

jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build action
        id: build
        run: |
          npm run prepare

          # We should ensure that the working directory does not include any
          # uncommitted changes which would indicate that the commit was not
          # properly prepared.
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo "$status"
            exit 1
          fi

      - name: Notify if build is not fully committed
        if: ${{ failure() && steps.build.outcome == 'failure' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "The current commit does not include an up-to-date build of the Jira create issue custom GitHub Action. Please run `npm run prepare` locally and commit all changes from the `dist` directory."
            })
