---
name: pre-commit

on:  # yamllint disable-line rule:truthy
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          curl -L "$(curl -s https://api.github.com/repos/mvdan/sh/releases/latest |
            grep -o -E -m 1 "https://.+?_linux_amd64")" > shfmt && \
            chmod +x shfmt && sudo mv shfmt /usr/bin/

      - name: pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Failure
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "pre-commit failed! Please ensure that pre-commit doesn't report any error."
            })
